
S" src/spf_forthproc_hl.f" INCLUDED
S" src/spf_except.f"       INCLUDED
S" src/spf_print.f"        INCLUDED

S" src/compiler/spf_parser.f"        INCLUDED
S" src/compiler/spf_read_source.f"   INCLUDED

4 CONSTANT CELL
USER S0
: CELLS CELL * ;
: DEPTH SP@ S0 @ - ;
: <> = 0= ;

VARIABLE ACTUAL-DEPTH			\ STACK RECORD
CREATE ACTUAL-RESULTS 80 ALLOT

: POOL-INIT 
    DECIMAL
    SP@ S0 !
    4 ALIGN-BYTES !
;

: EMPTY-STACK S0 @ SP! ;

: ERROR		\ ( C-ADDR U c-addr u -- ) DISPLAY AN ERROR MESSAGE FOLLOWED BY
		\ THE LINE THAT HAD THE ERROR.
   2SWAP
   TYPE TYPE CR			\ DISPLAY LINE CORRESPONDING TO ERROR
   EMPTY-STACK				\ THROW AWAY EVERY THING ELSE
;

: ->		\ ( ... -- ) RECORD DEPTH AND CONTENT OF STACK.
   DEPTH DUP ACTUAL-DEPTH !		\ RECORD DEPTH
   ?DUP IF				\ IF THERE IS SOMETHING ON STACK
      0 DO ACTUAL-RESULTS I CELLS + ! LOOP \ SAVE THEM
   THEN ;

: }T		\ ( ... addr u -- ) COMPARE STACK (EXPECTED) CONTENTS WITH SAVED
      \ (ACTUAL) CONTENTS.
   2>R
   DEPTH ACTUAL-DEPTH @ = IF		\ IF DEPTHS MATCH
      DEPTH ?DUP IF			\ IF THERE IS SOMETHING ON THE STACK
         0  DO				\ FOR EACH STACK ITEM
	        ACTUAL-RESULTS I CELLS + @	\ COMPARE ACTUAL WITH EXPECTED
	        <> IF S" INCORRECT RESULT: " 2R@ ERROR LEAVE THEN
         LOOP
      THEN
   ELSE					\ DEPTH MISMATCH
      S" WRONG NUMBER OF RESULTS: " ERROR
   THEN 2R> DROP DROP ;


S" tests/core.fr" INCLUDED

COMPILE-TESTS

: test POOL-INIT TESTER ;

' test 0 !
